- name: Install AstroNvim
  hosts: webservers
  become: yes
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Add Neovim repository (Debian/Ubuntu)
      apt_repository:
        repo: "ppa:neovim-ppa/unstable"
        state: present
        update_cache: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Neovim
      apt:
        name: "neovim"
        state: present

    - name: Install AstroNvim for each user
      include_tasks: install_astronvim_user.yml
      loop: "{{ users }}"
      loop_control:
        loop_var: current_user