- name: Install tmux
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Install tmux
      apt:
        name: tmux
        state: present

    - name: Check tmux version
      command: tmux -V
      register: tmux_version
      changed_when: false
