- name: Install Docker and Docker Compose
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose-plugin
        state: present

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        var: docker_version.stdout_lines

    - name: Verify Docker Compose installation
      command: docker compose version
      register: docker_compose_version
      changed_when: false

    - name: Display Docker Compose version
      debug:
        var: docker_compose_version.stdout_lines

