- name: Install Python 3.12
  hosts: webservers
  become: yes
  gather_facts: no

  vars:
    python_versions:
      - { version: "3.10.13", custom_path: "/opt/python3.10", config_flag: "--enable-optimizations --with-ensurepip=upgrade" }
      - { version: "3.11.7", custom_path: "/opt/python3.11", config_flag: "--enable-optimizations --with-ensurepip=upgrade" }
      - { version: "3.12.1", custom_path: "/opt/python3.12", config_flag: "--enable-optimizations --with-ensurepip=upgrade" }

  tasks:
    - name: Download Python
      get_url:
        url: "https://www.python.org/ftp/python/{{ item.version }}/Python-{{ item.version }}.tgz"
        dest: "/tmp/Python-{{ item.version }}.tgz"
      loop: "{{ python_versions }}"

    - name: Extract Python source
      unarchive:
        src: "/tmp/Python-{{ item.version }}.tgz"
        dest: "/tmp"
        remote_src: yes
      loop: "{{ python_versions }}"

    - name: Build and install Python
      shell: |
        ./configure {{ item.config_flag }} --prefix={{ item.custom_path }} &&
        make -j $(nproc) &&
        make altinstall
      args:
        chdir: "/tmp/Python-{{ item.version }}"
        creates: "{{ item.custom_path }}"
      async: 1800
      poll: 5
      loop: "{{ python_versions }}"

    - name: Create a symbolic link for 'python'
      command: "update-alternatives --install /usr/bin/python python {{ python_versions[-1].custom_path }} 1"
