- name: Install ZSH
  hosts: webservers
  become: yes
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Install ZSH for each user
      include_tasks: install_zsh_user.yml
      loop: "{{ users }}"
      loop_control:
        loop_var: current_user